### PR TITLE
Changes to producer file to make it compatible with Node 12

### PR DESCRIPTION
**Pull request by davidtrihy**
I haven't fully tested this yet as the e2e tests fail on my machine - Kafka issue, it still failed on Node 6 without any issues, I said I'd put up the PR while I look into fixing my Kafka to test properly but if anyone can run the e2e tests to verify for me, the other tests pass fine.

This compiles on Node 6, 8, 10 and 12

### CODE REVIEW

**Comment by analytik** [comment]
Tested in Docker on Debian 9, Node 12.7, compilation and basic pub/sub functionality works correctly.

**Comment by codeburke** [comment]
+1. @webmakersteve can we get this merged in as it blocks migration to Node 12.

**Comment by krystianity** [comment]
lgtm

**Comment by brettkiefer** [comment]
Since Node 12 becomes the Active LTS for Node in two weeks, general desire for releasing this may increase across the user base. I'd love to see it merged.

**Comment by NikitaSedyx** [comment]
:+1: agreed with @brettkiefer

**Pull request merged**
