### PR TITLE
Update TS defs with AdminClient

### PR DESCRIPTION
**Pull request by alexander-alvarez**
Follows up #504

### CODE REVIEW

**Comment by alexander-alvarez** [comment]
@webmakersteve mind taking a look at this?

**Comment by webmakersteve** [comment]
AdminClient isn't ready just yet :stuck_out_tongue: but we'll see how far I can get today!

**Comment by webmakersteve** [comment]
PR looks good otherwise, but you may need to add a few things when I'm done.

**Comment by alexander-alvarez** [comment]
No worries, just hit me up when you need me to add to it.

**Comment by webmakersteve** [comment]
I updated em myself when I added the new methods :)

**Pull request merged**
