### PR TITLE
Fixes for node 12

### PR DESCRIPTION
**Pull request by donjuandem**
Since you seem to have some trouble updating the npm versions, I tried to install the package manually but still got errors while building (namely a lint error and a problem with the librd-kafka dependency).

Luckily both problems were easily fixed. The last one by updating the dependency to a version where the (apparently OSX-related) bug was fixed (the current RC).

### CODE REVIEW

**Comment by iradul** [comment]
What is this?

**Comment by donjuandem** [comment]
Obviously a Pull Request... Could you be more specific?

**Comment by IdanAdar** [comment]
@iradul you have previously merged support for Node 12, is this still needed?

**Comment by analytik** [comment]
@donjuandem while the effort is appreciated, changing a number from "10" to "12" in travis config doesn't make it compatible with Node.js v12. 

The actual fix was done here: https://github.com/Blizzard/node-rdkafka/pull/665/files

**Comment by donjuandem** [comment]
@analytik yeah, of course the apparent problems were fixed elsewhere, that was not my point. I just wanted to get it running with node 12 and it seems this PR and my actions kind of helped to make this happen faster :wink: So I'm happy with that :grin:

But since you published a new version: I tried it out and it fails with linker errors at runtime on my machine.

So if you don't need this PR, just delete it, I honestly don't mind. I just wanted to contribute back and was looking for consistency.

In general, it would be more useful for you to get working versions of your lib continouusly (especially regarding the current one) instead of spending time on vetting some tiny-ass bullshit stuff, like this pr of mine, but just my 2 cents :relaxed:

So, stay tuned, keep improving and yeah, if you need something else feel free to ask

**Comment by IdanAdar** [comment]
Okay, that was weird. 

Anyway, for me at least it’s still not working on Node12. 
https://github.com/Blizzard/node-rdkafka/issues/712
https://github.com/Blizzard/node-rdkafka/issues/713

**Comment by iradul** [comment]
> Obviously a Pull Request... Could you be more specific?

Sorry, it has lots of different updates in a single PR. Setting `@circle/node-rdkafka` to the package name doesn't look ok.
Anyway, since all suggested fixes are pretty much already committed I'll close this.

**Pull request closed without merging**
