### PR TITLE
Travis CI: Add Node.js 18 & fix a few deprecations

### PR DESCRIPTION
**Pull request by cclauss**
Screenshot 2022-06-30 at 13 01 08

### CODE REVIEW

**Comment by yunnysunny** [comment]
All test on travis ci is skip for wrong stage name checking on it. This is one reason for swithing to github action. Another one is travis ci is not free now.

**Comment by cclauss** [comment]
Perhaps Blizzard has a paid subscription to Travis CI.  On fixing the branch name, it seems like only `make lint` fails.

**Comment by yunnysunny** [comment]
I have fixed it in https://github.com/Blizzard/node-rdkafka/pull/861 , but I closed it since github action pull request was committed.

**Comment by cclauss** [comment]
No Travis CI credits left... https://app.travis-ci.com/github/Blizzard/node-rdkafka/jobs/575459935

**Pull request closed without merging**
