### PR TITLE
Update librdkafka from 1.8.2 -> 1.9.2

### PR DESCRIPTION
**Pull request by GaryWilber**
Changes:
- librdkafka 1.9.2
     - https://github.com/edenhill/librdkafka/releases/tag/v1.9.0
     - https://github.com/edenhill/librdkafka/releases/tag/v1.9.1
     - https://github.com/edenhill/librdkafka/releases/tag/v1.9.2
- Update windows-install.py script due to path change related to MSVS v142 build tools
- Minor update to librdkafka-defs-generator.js script to fix issues related to some new comments in the rdkafka c++ files

### CODE REVIEW

**Comment by parkjh** [comment]
@GaryWilber I'm not a maintainer who can approve this pr but I don't suppose librdkafka can be updated to 1.9.1?
https://github.com/edenhill/librdkafka/releases/tag/v1.9.1 as a m1 laptop user, it'd be very much appreciated... 🙏

**Comment by GaryWilber** [comment]
@parkjh I updated it

**Comment by robinfehr** [comment]
we'd love to see that merged as well!

**Comment by sharmakhushboo** [comment]
@iradul could you please review this pr? We are also looking forward to consume this change.

**Comment by sharmakhushboo** [comment]
@webmakersteve may be you can help us with the review/merge here?

**Comment by sharmakhushboo** [comment]
@eandersson / @BlizzTom would you be able to help us here?

**Comment by ahmedbisht** [comment]
who can help merge this? thanks

**Comment by hedasilv** [comment]
@eandersson, @BlizzTom, @webmakersteve, who could help us get this pull request approved? We are looking forward to getting these updates in our app. Thanks a lot!

**Comment by iradul** [comment]
Thank you @GaryWilber !

**Pull request merged**
