### PR TITLE
Fake seek (experiment for discussion)

### PR DESCRIPTION
**Pull request by edoardocomar**
Tried adding an e2e test that uses assign with offset to mimic a seek function, i.e. issue #52 
This is what @edenhill hinted at I presume.

Problem is, this test passes using librdkafka 0.9.1 but fails with all subsequent releases we have tried (the consume method does not receive messages).

PR opened for discussion ...

developed with @mimaison

### CODE REVIEW

**Comment by webmakersteve** [comment]
I upgraded to 0.9.4 in the most recent release. Can you rebase this so we can see how the test works?

**Comment by edoardocomar** [comment]
Thanks, we will take a look in a few days

**Comment by mimaison** [comment]
Seek support was added in librdkafka's C++ API: https://github.com/edenhill/librdkafka/issues/1001
Instead of using this assign trick, it's probably better to directly rely on the C++ call to seek to a particular offset.

**Comment by michallevin** [comment]
I am also having issues using assign to seek to an offset - it seems to seek correctly, but does not consume all of the following offsets consistently (it can consume the 2 following offsets, the 50 following offsets, the 200 following offsets, etc). 

Can anyone confirm this behavior?

`var Kafka = require('node-rdkafka');

var topicName = 'Test';

var consumer = new Kafka.KafkaConsumer({
  //'debug': 'all',
  'metadata.broker.list': 'localhost:9092',
  'group.id': 'rdkafka-101',
  'enable.auto.commit': false
  //'offset.store.method': 'broker'
}, {
  'auto.offset.reset': 'beginning'
});

//logging debug messages, if debug is enabled
consumer.on('event.log', function(log) {
  console.log(log);
});

//logging all errors
consumer.on('event.error', function(err) {
  console.error('Error from consumer');
  console.error(err);
});

consumer.on('ready', function(arg) {
  console.log('consumer ready.' + JSON.stringify(arg));
  consumer.subscribe([topicName]);
  consumer.assign([ { topic: topicName, partition: 0, offset: 150 } ]);
  //start consuming messages
  consumer.consume();
});

consumer.on('data', function(m) {
  // Output the actual message contents
  //console.log(m.value.toString());
  console.log("topic " + m.topic);
  console.log("offset: " + m.offset);
});

consumer.on('disconnected', function(arg) {
  console.log('consumer disconnected. ' + JSON.stringify(arg));
});

//starting the consumer
consumer.connect();
`

**Comment by webmakersteve** [comment]
I am beginning to work on this branch, which should implement seek in the legacy consumer.

https://github.com/Blizzard/node-rdkafka/tree/legacy-consumer

**Comment by edoardocomar** [comment]
Thanks @webmakersteve - I see from 
https://github.com/edenhill/librdkafka/issues/1001
that seek is now available on the new C++ consumer.

Why should node-rdkafka use the legacy one ?

**Comment by webmakersteve** [comment]
I'd like to do both if I can. This commit added seek into the kafka consumer:

https://github.com/Blizzard/node-rdkafka/commit/1da221d53fc27b54f6b9537e17134f450545b917

**Comment by webmakersteve** [comment]
Closing PR as it has been implemented in librdkafka and added to master.

**Pull request closed without merging**
