### PR TITLE
Manual topic creation for transaction tests

### PR DESCRIPTION
**Pull request by helio-frota**
This commit adds code for manual topic creation when running
transaction tests.

This helps to run the tests in different environments other
than localhost.

We can use the environment variables to adjust the settings
if needed.

### CODE REVIEW

**Comment by helio-frota** [comment]
results both on remote environment and localhost:

remote:
```
 make e2e


  Transactional Producer
    ✓ should init transactions (1428ms)
    ✓ should complete transaction (5223ms)
    abort transaction
      ✓ should consume committed and uncommitted for read_uncommitted (8802ms)
      ✓ should consume only committed for read_committed (9546ms)
      ✓ should abort transaction (402ms)
      ✓ should consume only committed (9526ms)


  6 passing (41s)
```

localhost:

```
make e2e


  Transactional Producer
    ✓ should init transactions (2056ms)
    ✓ should complete transaction (144ms)
    abort transaction
      ✓ should consume committed and uncommitted for read_uncommitted (1143ms)
      ✓ should consume only committed for read_committed (2646ms)
      ✓ should abort transaction (113ms)
      ✓ should consume only committed (1658ms)


  6 passing (8s)
```

**Comment by mhdawson** [comment]
@iradul we are hoping to get the node-rdkafka tests running against the RH managed Kafka service. This is a first step. Is there anything we can do to help get this landed?

**Comment by helio-frota** [comment]
hi,

I understand that the code addition doesn't add any value to the current code. But also on other hand, it makes zero effect on the test results.

So when you have the time it would be nice to have this merged to help us to fix issues when running the integration tests against our environment which has restrictions with automatic topic creation.

thanks

**Comment by helio-frota** [comment]
hi, just a friendly ping on this :+1:

**Pull request closed without merging**
