### PR TITLE
Fixes #321

### LINKED ISSUE #321: Kafka consumer stream _read called after close and this.consumer is set to `null`
This causes an error thrown:
```
Uncaught TypeError: Cannot read property 'isConnected' of null
      at KafkaConsumerStream._read_message (node_modules/node-rdkafka/lib/kafka-consumer-stream.js:136:22)
      at Timeout._onTimeout (node_modules/node-rdkafka/lib/kafka-consumer-stream.js:180:16)
```

A check for `this.consumer` or presence should fix this?

### PR DESCRIPTION
**Pull request by sprijk**

### CODE REVIEW

**Comment by webmakersteve** [comment]
Can you add semicolons to the end of the statement?

**Comment by sprijk** [comment]
Due to @erik-stephens 's comment (https://github.com/Blizzard/node-rdkafka/issues/330#issuecomment-355831802), and the added semicolons, I am reopening this issue.

**Comment by oliviertassinari** [comment]
Great! Looking forward to have it released.

**Comment by webmakersteve** [comment]
Released!

**Comment by sprijk** [comment]
Yes!

2018-02-09 23:32 GMT+01:00 Stephen Parente <notifications@github.com>:

**Pull request merged**
