### PR TITLE
Read the download url of librdkafka from Windows environment variable

### PR DESCRIPTION
**Pull request by yunnysunny**
In Windows ,the download of the library of librdkafka may be so slowly, especially when you are in China. It may cost a long time to  download it. Sometime I have to wait for several hours. 
So I add an feature of reading the download url from environment variable.

### CODE REVIEW

**Comment by giulliano-bueno** [comment]
LGTM.

**Comment by yunnysunny** [comment]
@iradul Consider this pull request?

**Comment by iradul** [comment]
There is this `BUILD_LIBRDKAFKA` env variable that can be used to compile against system installed version of librdkafka. This doesn't work on Windows but I think it would be great if we could make it work and hence have consistency across platforms.

**Comment by yunnysunny** [comment]
I read the code of binding.gyp, the `BUILD_LIBRDKAFKA` is only an flag to indicate whether to building the source code with the shared library installed in OS already. And my pull request aims at supplying an URL to download nuget package. 
So I think it's two different thing.

**Comment by yunnysunny** [comment]
I  have rename `DOWNLOAD_BASE_URL_LIB_RDKAFKA` to `BUILD_LIBRDKAFKA`.

**Comment by iradul** [comment]
Let's call this variable `NODE_RDKAFKA_NUGET_BASE_URL` and also please leave README file unchanged, I'll update it after I merge this PR.

**Comment by yunnysunny** [comment]
done

**Comment by yunnysunny** [comment]
Expecting this merge can be published to npm. We can not bear the network in China now.

**Comment by iradul** [comment]
@yunnysunny I just released the new version

**Pull request merged**
