### PR TITLE
Upgrade librdkafka to 1.3.0

### PR DESCRIPTION
**Pull request by tarvip**
In addition to new features it fixes https://github.com/edenhill/librdkafka/issues/2363

[Release notes](https://github.com/edenhill/librdkafka/releases/tag/v1.3.0)

### CODE REVIEW

**Comment by iradul** [comment]
I don't see `librdkafka` field update in `package.json`

**Comment by solsson** [comment]
On what platforms and node versions did you run npm install? I fail with Debian Buster and Node.js 12.16.0:

```
[0m[91m/home/node/.cache/node-gyp/12.16.0/include/node/v8.h: In instantiation of 'void v8::PersistentBase<T>::SetWeak(P*, typename v8::WeakCallbackInfo<P>::Callback, v8::WeakCallbackType) [with P = Nan::ObjectWrap; T = v8::Object; typename v8::WeakCallbackInfo<P>::Callback = void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)]':
../node_modules/nan/nan_object_wrap.h:65:61: required from here
/home/node/.cache/node-gyp/12.16.0/include/node/v8.h:10226:16: warning: cast between incompatible function types from 'v8::WeakCallbackInfo<Nan::ObjectWrap>::Callback' {aka 'void (*)(const v8::WeakCallbackInfo<Nan::ObjectWrap>&)'} to 'Callback' {aka 'void (*)(const v8::WeakCallbackInfo<void>&)'} [-Wcast-function-type]
[0m[91mmake: *** [node-librdkafka.target.mk:130: Release/obj.target/node-librdkafka/src/producer.o] Error 1
gyp ERR! build error
[0mrm 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate
make: Leaving directory '/usr/local/lib/node_modules/node-rdkafka/build'
```

**Comment by tarvip** [comment]
My mistake, I was using 1.2.2 upgrade PR as example.  Should be good now.

**Comment by yunnysunny** [comment]
librdkafka 1.3 brings an amazing feature of static group membership, which will reduce the chance of unnecessary rebalances. The official reference can be found here [KIP-345](https://cwiki.apache.org/confluence/display/KAFKA/KIP-345%3A+Introduce+static+membership+protocol+to+reduce+consumer+rebalances).
So I expected the release with this pull request.

**Comment by iradul** [comment]
Thank you @tarvip

**Pull request merged**
