### PR TITLE
Provisional Header support for producing and consuming messages with Headers

### PR DESCRIPTION
**Pull request by davidtrihy**
I'm just looking for some feedback and conversation about this PR for producing and consuming with headers in node-rdkafka. 

I currently have a PR open on librdkafka https://github.com/edenhill/librdkafka/pull/1959 for support in the C++ library which may go through some changes when Magnus Edenhill gets around to providing feedback on it.

Assuming this is the implementation that we will go with I'd like to see if these changes proposed in this PR would be suitable for merging into node-rdkafka when librdkafka has Header support.

Most notably I would like feedback on the node bindings and if that is the correct way to translate objects from one language to the other. 

Thanks!

### CODE REVIEW

**Comment by davidtrihy** [comment]
I just realised because I updated the submodule git hash this will not build but from my own testing I got all the integration tests to pass.

**Comment by webmakersteve** [comment]
The interface looks totally fine, and would be happy to merge it when we get a version of `librdkafka` released with the correct interface :) 

Thanks for the PR!

**Comment by davidtrihy** [comment]
@webmakersteve I'll try and prioritise pushing this over the line when work starts to get a little less hectic.

**Comment by davidtrihy** [comment]
@webmakersteve I have what I believe to be the correct changes but one of the new tests added is failing with my changes, can you advise?

Also this is with the changes that were merged into master so I'm not sure how you want to proceed regarding this review?

**Comment by davidtrihy** [comment]
Let me rewrite the history for this branch as well, it's a bit messy :)

**Comment by alexander-alvarez** [comment]
@davidtrihy that's just a failing test case that @webmakersteve merged for the admin tests in https://github.com/Blizzard/node-rdkafka/pull/519

**Comment by mimaison** [comment]
I agree, the proposed API looks fine. Ideally I'd prefer `opaque` to stay the last argument of `produce()` but I don't think it's possible without breaking compatibility =(

@davidtrihy It looks like some of the cpplint errors are caused by code added in this PR. Also can you rebase your changes on top of master? so the PR only has your commits

I think the test failure has been fixed already in master. Hopefully after a rebase Travis will pass!

**Comment by Fr8Traindb** [comment]
any update on this?

**Comment by Fr8Traindb** [comment]
@webmakersteve is there anything the community can do to help this along?
Thanks.

**Comment by davidtrihy** [comment]
@Fr8Traindb sorry forgot about this open PR, let me sort out the issues open in the PR, hopefully the feedback is quick and we can get it merged

**Comment by Fr8Traindb** [comment]
@davidtrihy, how is this going so far?

**Comment by Fr8Traindb** [comment]
Sorry to keep asking about this, but I would really love this feature!  Would appreciate any updates you have.

**Comment by davidtrihy** [comment]
I added a new PR fixing hopefully all of the issues with the previous PR, no lint errors and the commits are in check, https://github.com/Blizzard/node-rdkafka/pull/579

**Pull request closed without merging**
