### PR TITLE
Revised consumer and producer examples

### PR DESCRIPTION
**Pull request by edoardocomar**
The consumer example uses the Flowing mode.

codeveloped with @mimaison

### CODE REVIEW

**Comment by webmakersteve** [comment]
Thanks for the PR! Just one comment :)

**Comment by edoardocomar** [comment]
Thanks @webmakersteve did you mean to add a comment or comment that this PR is just one comment :-) :-) ?

**Comment by webmakersteve** [comment]
I added one in the code review section - I think I forgot to push publish.

After we get that fixed I can merge it.

**Comment by mimaison** [comment]
Thanks @webmakersteve for the review !
I've removed the call to getMetadata()

**Pull request merged**
