### PR TITLE
Update to librdkafka 2.3.0

### PR DESCRIPTION
**Pull request by riley-pikus**
Submodule updated to point towards https://github.com/confluentinc/librdkafka/releases/tag/v2.3.0

### CODE REVIEW

**Comment by GaryWilber** [comment]
@riley-pikus Thanks for the PR. Could you delete and recreate the `package-lock.json` file by running `npm install --lockfile-version 2`. The build checks failed, likely due to an compat issue in older node/npm releases. Sticking with lock file v2 might fix it.

**Comment by riley-pikus** [comment]
> @riley-pikus Thanks for the PR. Could you delete and recreate the `package-lock.json` file by running `npm install --lockfile-version 2`. The build checks failed, likely due to an compat issue in older node/npm releases. Sticking with lock file v2 might fix it.

I was in the middle of doing this locally but it looks like you beat me to it 😀. Want me to update the CONTRIBUTING.md? There is also step 6 of running e2e tests but that command doesn't exist within package.json

**Comment by GaryWilber** [comment]
> > @riley-pikus Thanks for the PR. Could you delete and recreate the `package-lock.json` file by running `npm install --lockfile-version 2`. The build checks failed, likely due to an compat issue in older node/npm releases. Sticking with lock file v2 might fix it.
> 
> I was in the middle of doing this locally but it looks like you beat me to it 😀. Want me to update the CONTRIBUTING.md? There is also step 6 of running e2e tests but that command doesn't exist within package.json

Yea could you update that. I will make a PR to release `v2.18.0` of this package after this is merged in. Thanks

**Comment by riley-pikus** [comment]
> > > @riley-pikus Thanks for the PR. Could you delete and recreate the `package-lock.json` file by running `npm install --lockfile-version 2`. The build checks failed, likely due to an compat issue in older node/npm releases. Sticking with lock file v2 might fix it.
> > 
> > 
> > I was in the middle of doing this locally but it looks like you beat me to it 😀. Want me to update the CONTRIBUTING.md? There is also step 6 of running e2e tests but that command doesn't exist within package.json
> 
> Yea could you update that. I will make a PR to release `v2.18.0` of this package after this is merged in. Thanks

Done, appreciate the quick turn around on this release @GaryWilber!

**Pull request merged**
