### PR TITLE
Update librdkafka from 1.7.0 -> 1.8.2

### PR DESCRIPTION
**Pull request by GaryWilber**
Same story as [last time](https://github.com/Blizzard/node-rdkafka/pull/915). All the unit & e2e tests are passing for me besides the deleteTopic one, which is failing due to me testing on windows & known kafka bugs ([1](https://issues.apache.org/jira/browse/KAFKA-7020), [2](https://issues.apache.org/jira/browse/KAFKA-8811))

The largest change in this update is related to the nuget package. [v1.8.0](https://github.com/edenhill/librdkafka/releases/tag/v1.8.0) introduced some packaging changes, which required changes to the `windows-install.py` script.

Changes:
- librdkafka 1.8.2
- Update `windows-install.py` script to support the new packaging format
- Minor update to `librdkafka-defs-generator.js` script for better CRLF line ending support

### CODE REVIEW

**Comment by GaryWilber** [comment]
@iAlex97 fyi since you were interested in this

**Comment by GaryWilber** [comment]
@iradul Could you review this when you have the chance. Thank you

**Comment by iradul** [comment]
It looks good. Thank you @GaryWilber 
Sorry for the long wait. I've been busy lately.

**Comment by iAlex97** [comment]
@iradul sorry to be bothering, but can you also do a npm release like you did with 1.7.0?

**Pull request merged**
