### PR TITLE
Enhance the travis-ci script

### PR DESCRIPTION
**Pull request by yunnysunny**
I think there are some mistakes about travis-ci :
First, the item of `matrix.include` can only specify one version of node. If multiple given, only the first one will been processed.
Second, the original travis-ci config mixes the test script with deploy script. I think it will be more clear if we separate each other.
Since the reasons mentioned above, I dropped the use of `matrix.include`,  used `jobs.include` instead. There are 4 stages defined in yml file, its names are `test_on_mac` `test_on_win` `create_doc` `publish_num`. The default stage `test` is not specified in yml file, but will also been triggered, and been run on multiple node versions. 
At the end, I add the support of building on windows. Someone said that the building was broken on windows, and now we can test on windows when code pushed. Windows builds are in early access stage in travis-ci , and has some problems, such as the lack of ca files, which may lead to download failed from https link, so I modify some code on python to ignore the ssl verify. Notice that more time will been used when build on windows, I found it takes 4 minutes on travis-ci.
By the way, the readme file tell us to install `windows-build-tools` with vs2015, it may lead to fail for that the node with version greater that 6.x cant not build addon with vs2015.
After testing many times and failed many times, I  finish the enhancement finally.

### CODE REVIEW

**Comment by yunnysunny** [comment]
The travis-ci will fail on windows for the issue #591

**Comment by webmakersteve** [comment]
Can you rebase this and comment? It looks good to me, and I merged in the windows fix.

**Comment by yunnysunny** [comment]
I have resolve the conflict in README.md.

**Comment by webmakersteve** [comment]
I'm going to merge this, but it looks like there is a failure on Windows right now. Because of that I don't want those builds to fail the entire CI job so I will be making an adjustment to only warn on windows failures rather than fail the entire build. Once it is more stable I will make it fail the entire build when windows builds fail.

Thanks for the contribution!

**Comment by yunnysunny** [comment]
The current `librdkafka` defined in `package.json` version is `1.0.0.2`, the the version can't been found in `nuget`,  so the build failed in Windows.
I think you have given the wrong version, the newest version on `nuget` is `1.0.1`.

**Comment by yunnysunny** [comment]
I have pulled a new request #634 to resolve it.

**Pull request merged**
