### PR TITLE
Support for Node.js 12.x

### LINKED ISSUE #606: Support for Node.js 12.x
Node-rdkafka 2.6.1 does not build with Node.js 12 under Debian 9.

Example output:
```In file included from /home/node/.node-gyp/12.0.0/include/node/v8-internal.h:14:0,
                 from /home/node/.node-gyp/12.0.0/include/node/v8.h:25,
                 from /home/node/.node-gyp/12.0.0/include/node/node.h:63,
                 from ../node_modules/nan/nan.h:53,
                 from /home/node/.npm/lib/node_modules/node-rdkafka/src/common.h:13,
                 from ../src/common.cc:13:
/home/node/.node-gyp/12.0.0/include/node/v8.h:3416:55: note: declared here
   V8_DEPRECATE_SOON("Use maybe version", Local<Value> Get(uint32_t index));
                                                       ^
/home/node/.node-gyp/12.0.0/include/node/v8config.h:322:3: note: in definition of macro ‘V8_DEPRECATE_SOON’
   declarator __attribute__((deprecated(message)))
   ^~~~~~~~~~
../src/common.cc:516:31: warning: comparison between ‘enum rd_kafka_resp_err_t’ and ‘enum RdKafka::ErrorCode’ [-Wenum-compare]
           if (err != RdKafka::ERR_NO_ERROR) {
                               ^~~~~~~~~~~~
node-librdkafka.target.mk:126: recipe for target 'Release/obj.target/node-librdkafka/src/common.o' failed
rm 11a9e3388a67e1ca5c31c1d8da49cb6d2714eb41.intermediate
make: Leaving directory '/home/node/.npm/lib/node_modules/node-rdkafka/build'
make: *** [Release/obj.target/node-librdkafka/src/common.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/node/nodejs/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:196:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:256:12)
gyp ERR! System Linux 4.14.88-coreos
gyp ERR! command "/home/node/nodejs/bin/node" "/home/node/nodejs/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/node/.npm/lib/node_modules/node-rdkafka
gyp ERR! node -v v12.0.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-rdkafka@2.6.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-rdkafka@2.6.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/node/.npm/_logs/2019-04-24T06_32_28_180Z-debug.log
```

Example (simplified) Dockerfile:
```
FROM debian:stretch

RUN groupadd --gid 3333 node \
    && useradd --uid 3333 --gid node --shell /bin/bash --create-home node

ENV TERM=xterm

RUN apt-get update && apt-get install sudo && echo "node ALL=(ALL) NOPASSWD:/usr/bin/apt-get,/usr/bin/dpkg,/bin/rm" >> /etc/sudoers

USER node

ENV NODE_VERSION=12.0.0
ENV PATH="${PATH}:/home/node/.npm/bin:/home/node/nodejs/bin"
ENV NODE_PATH="/home/node/.npm/lib/node_modules"

RUN sudo apt-get install -y --no-install-recommends xz-utils curl ca-certificates \
    && mkdir /home/node/node_modules \
    && NODEJS_NAME="node-v${NODE_VERSION}-linux-x64" \
    && NODEJS_TAR="${NODEJS_NAME}.tar.xz" \
    && cd /home/node && curl "https://nodejs.org/dist/v${NODE_VERSION}/${NODEJS_NAME}.tar.xz" -o "/home/node/${NODEJS_TAR}" \
    && tar xf ${NODEJS_TAR} \
    && mv "${NODEJS_NAME}" nodejs \
    && rm "${NODEJS_TAR}" \
    && npm config set prefix "/home/node/.npm" \
    && npm i -g yarn

RUN sudo dpkg -l > /tmp/packages-before.txt \
    && sudo apt-get install -y --no-install-recommends \
        python \
        librdkafka-dev librdkafka++1 librdkafka1 \
        libssl1.0-dev liblz4-dev libsasl2-dev \
        libpthread-stubs0-dev \
        gcc g++ make build-essential pkg-config \
        git-core \
        ca-certificates \
        curl \
        less \
        nano \
        netcat \
        ssh-client \
        tcpdump \
        vim \
        netcat \
        net-tools \
        libpq-dev libpq5 \
    && npm install -y -g node-gyp

RUN npm install -y -g node-rdkafka@2.6.1 \
    && npm install -y -g pg-native@3.0.0 \
    && sudo apt-get remove -y \
        gcc g++ make pkg-config xz-utils \
        binutils cpp cpp-6 dpkg-dev g++-6 gcc-6 libasan3 libatomic1 \
        libc-dev-bin libc6-dev libcc1-0 libcilkrts5 libdpkg-perl libgcc-6-dev \
        libglib2.0-0 libgomp1 libisl15 libitm1 liblsan0 libmpc3 libmpfr4 \
        libmpx2 libquadmath0 libstdc++-6-dev libtsan0 libubsan0 linux-libc-dev \
        libsasl2-dev libpthread-stubs0-dev liblz4-dev \
        librdkafka-dev libssl1.0-dev \
    && sudo apt-get install --no-install-recommends -y libgomp1 \
    && sudo apt-get autoremove -y \
    && sudo apt-get clean \
    && sudo dpkg -l > /tmp/packages-after.txt \
    && sudo rm -rf /var/lib/apt/lists/*
```

### PR DESCRIPTION
**Pull request by lrecknagel**
Apply Nan changes required by >= NodeJS 12.x

Fixes #606

### CODE REVIEW

**Comment by kleme** [comment]
Any chance of moving forward with this pull request?
We have a pretty big scale deployment in Unity using node.js and node-rdkafka and
we try to keep up with the latest node.js versions.
Not having node-rdkafka support node.js 12 is blocking us from upgrading.

**Comment by webmakersteve** [comment]
Can you remove the yarn lock file? After that I can merge in.

**Comment by lrecknagel** [comment]
Should be fixed now. Thanks for taking care!

**Comment by analytik** [comment]
One question though, with this merged,
```
  "engines": {
    "node": ">=12.0.0"
  }
```

Won't npm disallow people from running node-rdkafka on Node.js < 12.0.0? I assume that's bound to make some people unhappy. If the changes really won't compile on older Node.js versions, we could bump node-rdkafka itself to 3.0.0 and continue with making breaking changes, if there are any planned?

**Comment by ankon** [comment]
As far as I understand that field, it is more of an advice, rather than a requirement. One can use things like https://www.npmjs.com/package/check-node-version to enforce it. But, I would agree that setting this is maybe a bit too strong a signal, especially since Travis is still checking on older versions as well :)

**Comment by markusdanek** [comment]
Can you create a new release for this PR?
We are desperately waiting for the v12 support 😄 

Thanks @lrecknagel & @webmakersteve

**Comment by lrecknagel** [comment]
Sorry for the `engines` field. I mixed that up.
Should be easy fixable ^^

**Comment by analytik** [comment]
Does everyone's master brain compile successfully? When I run `git clone https://github.com/lrecknagel/node-rdkafka.git -b node12Support` with rdkafka 0.11.6 it works. 

But with 1.0.0-RC or 1.0.1 from master branch, it dies [like so](https://gist.github.com/analytik/19730ac500791aaf306167c07d8500de). I can't see anything specific causing it though.

**Comment by Aditya-Viswanadha** [comment]
When is this going to be released.

**Comment by vipul657** [comment]
I am still getting errors upon pulling from master branch 

this is my dependency in package.json
"node-rdkafka": "git+https://github.com/Blizzard/node-rdkafka.git#master"
 The build is still failing 

So I had to pull from the the specific commit 
"node-rdkafka": "git+https://github.com/Blizzard/node-rdkafka.git#2ce4dff4aa99f569c826ff6487ec91657e0a3a76"

This approach lets me build successfully.Probably subsequent commits are creating some issue, anyone having idea about this?

**Comment by rocketraman** [comment]
> As far as I understand that field, it is more of an advice, rather than a requirement.

@ankon @lrecknagel  No, that is not true. It actually sets it as a requirement. It can be ignored e.g. `yarn install --ignore-engines` but that isn't the default behavior.

See https://github.com/Blizzard/node-rdkafka/issues/656.

**Comment by IdanAdar** [comment]
PR to reduce it to Node 8: https://github.com/Blizzard/node-rdkafka/pull/657

**Comment by brettkiefer** [comment]
node-rdkafka 2.7.1 doesn't install for me under Node 12, either.

```
nvm use 12
npm init -y
npm install node-rdkafka
```

Attempts to install node-rdkafka 2.7.1:

```
> node-rdkafka@2.7.1 install /home/server/node_modules/node-rdkafka
> node-gyp rebuild
```

 but fails. It's a little noisy with deprecation warnings, but the actual errors appear to be:

```
../src/producer.cc:453:68: error: no matching function for call to 'v8::Value::ToObject()'
         v8::Local<v8::Object> header = v8Headers->Get(i)->ToObject();
                                                                    ^
In file included from /home/server/.node-gyp/12.7.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from /home/server/node_modules/node-rdkafka/src/producer.h:13,
                 from ../src/producer.cc:13:
/home/server/.node-gyp/12.7.0/include/node/v8.h:2539:44: note: candidate: v8::MaybeLocal<v8::Object> v8::Value::ToObjec
t(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Object> ToObject(
                                            ^
/home/server/.node-gyp/12.7.0/include/node/v8.h:2539:44: note:   candidate expects 1 argument, 0 provided
In file included from /home/server/.node-gyp/12.7.0/include/node/v8-internal.h:14:0,
                 from /home/server/.node-gyp/12.7.0/include/node/v8.h:25,
                 from /home/server/.node-gyp/12.7.0/include/node/node.h:63,
                 from ../../nan/nan.h:54,
                 from /home/server/node_modules/node-rdkafka/src/producer.h:13,                                                         from ../src/producer.cc:13:
/home/server/.node-gyp/12.7.0/include/node/v8.h:2553:31: note: candidate: v8::Local<v8::Object> v8::Value::ToObject(v8:
:Isolate*) const
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^                                                                                       /home/server/.node-gyp/12.7.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
/home/server/.node-gyp/12.7.0/include/node/v8.h:2553:31: note:   candidate expects 1 argument, 0 provided
                 Local<Object> ToObject(Isolate* isolate) const);
                               ^
/home/server/.node-gyp/12.7.0/include/node/v8config.h:311:3: note: in definition of macro 'V8_DEPRECATED'
   declarator __attribute__((deprecated(message)))
   ^
../src/producer.cc:457:66: error: no matching function for call to 'v8::Object::GetOwnPropertyNames()'
         v8::Local<v8::Array> props = header->GetOwnPropertyNames();
                                                                  ^
In file included from /home/server/.node-gyp/12.7.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:54,
                 from /home/server/node_modules/node-rdkafka/src/producer.h:13,
                 from ../src/producer.cc:13:
/home/server/.node-gyp/12.7.0/include/node/v8.h:3541:43: note: candidate: v8::MaybeLocal<v8::Array> v8::Object::GetOwnP
ropertyNames(v8::Local<v8::Context>)
   V8_WARN_UNUSED_RESULT MaybeLocal<Array> GetOwnPropertyNames(
                                           ^
/home/server/.node-gyp/12.7.0/include/node/v8.h:3541:43: note:   candidate expects 1 argument, 0 provided
/home/server/.node-gyp/12.7.0/include/node/v8.h:3550:43: note: candidate: v8::MaybeLocal<v8::Array> v8::Object::GetOwnP
ropertyNames(v8::Local<v8::Context>, v8::PropertyFilter, v8::KeyConversionMode)
   V8_WARN_UNUSED_RESULT MaybeLocal<Array> GetOwnPropertyNames(
                                           ^
/home/server/.node-gyp/12.7.0/include/node/v8.h:3550:43: note:   candidate expects 3 arguments, 0 provided
```

Node 12.7.0 on Ubuntu 16.04.6 LTS.

NPM DOES install the package successfully under Node 10 on that same instance.

Does that match others' observations?

**Comment by analytik** [comment]
Yes. 2.7.0 and master up to recently (have not tested 2.7.1) fails on this block of code, [starting at 448 to 471](https://github.com/Blizzard/node-rdkafka/blob/master/src/producer.cc#L448). Commenting out makes it build and work successfully.

**Comment by lrecknagel** [comment]
Sorry again for the mixed up engines field. Hope the existing PR can merged soon!

For the errors on >= 12.7.0, can be due to again changed C++ interfaces.
I try to give it a try tmr.

Maybe its better to wait until a LTS landed and thus low-level interfaces are more stable.

**Comment by brettkiefer** [comment]
Thanks! It looks like I get the exact same errors as above in https://github.com/Blizzard/node-rdkafka/pull/610#issuecomment-514781762 on Node 12.0.0 as well, so I don't think there is an issue with changing interfaces between Node 12 versions.

It looks like that code wasn't merged in until 2.7.0 (from @analytik's [comment above](https://github.com/Blizzard/node-rdkafka/pull/610#issuecomment-514927370), we can trace that to https://github.com/Blizzard/node-rdkafka/commit/6065784faea0585d00c5196adb2f20cfd220f517), so it seems more likely that the base for your Node 12 fixes just didn't include that code, so you wouldn't have seen the errors?

**Comment by analytik** [comment]
Yes, I can confirm that the PR by @lrecknagel compiles on node 12.0 to 12.7 that I tested. But 2.7.0, 2.7.1 and anything in master branch does not compile, including the PR merge commit `6e22631a62e92f1165f5eeaf60a9dafdf826f071`. The reason being that the offending commit, `6065784` came later, after this PR was branched off, and as it wasn't rebased and retested before merging, it wasn't discovered earlier.

@davidtrihy, can you please try if you can compile the master branch on Node 12.x?

**Comment by davidtrihy** [comment]
@analytik I'm looking into it now to try and sort it out

**Comment by davidtrihy** [comment]
@analytik I got it compiling and opened a PR https://github.com/Blizzard/node-rdkafka/pull/665

I'm having issues running the end to end tests even without any changes, my local Kafka installation is broken so I'm gonna fix that and try and run the tests but if you could check out my branch and verify yourself locally, the changes are very small so I suspect it will all work fine. It compiles with Node 6, 8, 10 and 12.

**Comment by analytik** [comment]
@davidtrihy Thanks so much! I've tested it (simple pub/sub, not in production) and it works.

**Pull request merged**
